name: Maven CI/CD Pipeline with Docker

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }} # Path for settings.xml

    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        cp .github/workflows/settings.xml ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B clean install --file pom.xml

    - name: Upload JAR to GitHub Releases
      uses: softprops/action-gh-release@v2
      if: success()  # Ensures previous steps succeeded
      with:
        files: target/kinder-app-1.0.1-SNAPSHOT.jar
        tag_name: v1.0.1
        release_name: "Kinder App v1.0.1"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kinder-app-artifact
        path: target/kinder-app-1.0.1-SNAPSHOT.jar
        retention-days: 30

  docker:
          runs-on: ubuntu-latest
          needs: build  # Ensure Maven build completes before Docker build
          steps:
      
            - name: Checkout Repository
              uses: actions/checkout@v4
          
            - name: Download JAR from GitHub Release
              run: |
                curl -L -o kinder-app.jar https://github.com/vje123/python-kinder-app/releases/download/v1.0.1/kinder-app-1.0.1-SNAPSHOT.jar
          
            - name: Verify JAR File
              run: ls -lh kinder-app.jar
      
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
      
            - name: Build Docker Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/kinder-app:latest .
                docker tag ${{ secrets.DOCKER_USERNAME }}/kinder-app:latest ${{ secrets.DOCKER_USERNAME }}/kinder-app:v1.0.1
      
            - name: Push Docker Image to Docker Hub
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/kinder-app:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/kinder-app:v1.0.1
      
